apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "itvw-db-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "itvw-db-helm.selectorLabels" . | nindent 4 }}
